name: Build PyOdide
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: 3.11.2
      - run: |
          pip install pyodide-build>=0.23.0
          echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
      - run: pyodide build


      - name: set up node
        uses: actions/setup-node@master # v3.6.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Pyodide virtual environment
        run: |
          pyodide venv .venv-pyodide
          source .venv-pyodide/bin/activate
          pip install dist/*.whl
          pip install numpy
          pip install pandas
          pip install pytest
          pip install hypothesis

      - name: Test
        run: |
          source .venv-pyodide/bin/activate
          pytest test

        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Copy to AWS s3
        run: |
          aws s3 cp build/*.whl s3://flexatone/packages/

